openreferral/specification

LICENSE, README.md, TODO.md, datapackage.json
=> [WIP] Updated documentation in schema

datapackage.json
This is an update of PR #143.  Reverted to the original format "%Y" of the 'year_incorporated' field
=> Update: Changed datapackage.json to to conform to latest Table Schema spec

docs/about-HSDS.md
Restructuring so that we can have HSDS and HSDA co-existing, with respective About pages.
=> Changed name of file (and header) to spec HSDS

docs/index.md
=> Add index page to left nav as "About"

requirements.txt
#178 
Preview this change at http://docs.openreferral.org/en/178-long-fieldnames/hsda/hsda-search/
=> [#178] Update sphinxcontrib-opendataservices commit, to fix HSDA tables

datapackage.json
Fixed some reference typos and converted the address reference so that it references the physical and postal addresses rather than address which doesn't exist.
=> Fixed some foreign key references

docs/hsda/index.md
Until we have a strong reference implementation I am removing this section. I will work to get a v2.0 version up ASAP, and then we can add back.
=> Removing reference implementation

CODE_OF_CONDUCT.md, docs/hsds/changelog.md, docs/hsds/reference.md
Closes #310 
I've also pulled in the code of conduct from `master` so everything is up to date.
=> 310 reference text

datapackage.json, docs/hsds/changelog.md, examples/location.json, examples/organization_full.json, examples/service_at_location_full.json, examples/service_full.json, schema/address.json, schema/compiled/organization.json, schema/compiled/organization_package.json, schema/compiled/service.json, schema/compiled/service_at_location.json, schema/compiled/service_at_location_package.json, schema/compiled/service_package.json, schema/compiled/tabular.json, schema/location.json, schema/organization.json, schema/service.json
Closes #318 
@kindly I think this gets them all. I've left `service_at_locations` as is (and updated one of the descriptions from `services_at_location`, as this appears to be used somewhere in the `hsds_schema.py` script. Happy to update if we want to though.
=> 318 pluralisation

datapackage.json, schema/accessibility.json, schema/address.json, schema/attribute.json, schema/compiled/organization.json, schema/compiled/organization_package.json, schema/compiled/service.json, schema/compiled/service_at_location.json, schema/compiled/service_at_location_package.json, schema/compiled/service_package.json, schema/compiled/tabular.json, schema/contact.json, schema/cost_option.json, schema/funding.json, schema/language.json, schema/location.json, schema/meta_table_description.json, schema/organization.json, schema/organization_identifier.json, schema/phone.json, schema/program.json, schema/required_document.json, schema/schedule.json, schema/service.json, schema/service_area.json, schema/service_at_location.json, schema/taxonomy.json, schema/taxonomy_term.json
https://github.com/openreferral/specification/issues/330
Update JSON schema with descriptions on references.
=> Add descriptions to all relationship fields.

schema/compiled/service_with_definitions.json
#330
Add schema with nested definitions.  This from now on can automatically be done by `hsds_schema.py docs-all`.
Changelog can be done as part of #330 
=> Add service with definitions file.

docs/_static/json-example-format.js, docs/_static/jsonschema.css, docs/_static/renderjson.css, docs/_static/renderjson.js, docs/_templates/layout.html, docs/conf.py, docs/hsds/reference.md, requirements.in, requirements.txt
Closes #330 
[Preview](http://docs.openreferral.org/en/330-json-reference/hsds/reference.html)
=> 330 json reference

datapackage.json, docs/hsds/reference.md, examples/csv/meta_table_description.csv, examples/tabular.json, schema/compiled/service_with_definitions.json, schema/compiled/tabular.json, schema/meta_table_description.json
=> 344 meta table

docs/hsds/changelog.md, docs/hsds/uk_compliance.md, docs/index.md
Related to #353 
[Preview](http://docs.openreferral.org/en/uk-compliance/hsds/uk_compliance.html)
=> add uk compliance page

docs/conf.py
=> reduce sidebar depth

schema/openapi.json
#372 
Add format, per_page, postcode and proximity parameters
=> Add format, per_page, postcode and proximity parameters

docs/hsds/api_reference.md
=> Removed rogue bullets from API Reference page

docs/hsds/api_reference.md
Removed erroneous page parameter from / endpoint admonition and added details of the returned JSON object for the / endpoint
=> Amendments to API Reference page

docs/conf.py
Closes #364 
Fix issue with svg width; problem with path to theme_overrides.css file
=> docs/conf.py: Fix path to theme_overrides.css

docs/hsds/schema_reference.md
=> add taxonomy detail collapse

docs/hsds/schema_reference.md
=> add organization identifiers to schema reference

docs/faq.md, docs/hsds/changelog.md, docs/hsds/producing_sharing.md
=> 309 changelog

docs/extras/openapi30.json, docs/hsds/api_reference.md, docs/hsds/schema_reference.md, examples/base.json, schema/openapi.json
Looking at this, having a 3.0 branch and linking to that makes the most sense.
=> Change 3.0-dev to 3.0
